late/chroot_scripts/99-secure-boot.sh, late/scripts/oem_config.sh
remove the BIOS trash of MokSBStateSet entries at the end of OOBE
=> fixed BIOS bootorder issue

Dell/recovery_backend.py, Dell/recovery_common.py, late/scripts/SUCCESS-SCRIPT, ubiquity/dell-bootstrap.py
done FI process and passed with unit test.
=> regenerate the md5sum.txt during both ISO building and FI process

late/scripts/FAIL-SCRIPT, late/scripts/SUCCESS-SCRIPT
not only add dmesg.log file but also fix a grep command bug
=> add dmesg.log info

Dell/recovery_common.py
When selecting to create the recovery media, it will encounter the encoding issue when returning some UTF-8 string.
Please refer to https://bugs.launchpad.net/somerville/+bug/1710819 for more details.
=> Fix the encoding issue in oem-config.

po/zh_TW.po
Please check https://bugs.launchpad.net/somerville/+bug/1711294 for more details.
=> Translate more strings for zh_TW.

debian/changelog, debian/control
Signed-off-by: Yuan-Chen Cheng <yc.cheng@canonical.com>
=> add lvm2 and cryptsetup to dependency

debian/control
=> add dependencies for FDE

Dell/recovery_backend.py, Dell/recovery_common.py, Dell/recovery_gtk.py, debian/dell-recovery.templates, dell-restore-system, gtk/tool_selector.ui, ubiquity/dell-bootstrap.py, ubiquity/stepDellBootstrap.ui
Signed-off-by: chris Li Q <Chris.Li.Q@dell.com>
=> change code for add Dell Hybird Client part

late/chroot_scripts/03-ubuntu-drivers.sh
take care out put like below from ubuntu-drivers-common 1:0.8.1
$ ubuntu-drivers list
oem-fix-gfx-nvidia-powersavingmode
nvidia-driver-440, (kernel modules provided by nvidia-dkms-440)
oem-release
oem-somerville-meta
=> filter the output of `ubuntu-drivers list`

debian/changelog, ubiquity/dell-bootstrap.py, ubiquity/stepDellBootstrap.ui
=> 0002 enhance disk sort

debian/changelog, ubiquity/dell-bootstrap.py, ubiquity/dell-recovery.py
- full-automatic in oobe if it run in automatic mode.
- a new dev mode to enalbe full-automatic works in stage 1, 2 and recovery from hdd.
=> 0003 dev mode

debian/changelog, ubiquity/dell-bootstrap.py
Do not wake up network at stage 2 (issue #114).
=> do not wake up network at stage 2 (issue #114)

late/scripts/chroot.sh
remove $TARGET/pts if it's manually created for chroot.
=> stage2: remove directory $TARGET/pts

debian/changelog, debian/dell-recovery.templates, ubiquity/dell-bootstrap.py
cherry-pick chang from main branch.
=> 0008 focal recovery partition size hint2

Dell/recovery_common.py, ubiquity/dell-bootstrap.py
fix empty line in recovery-id and install-id file on DHC
fix unexpected behavior on Ubuntu+DCA(Nvidia Graphic)
=> change for DHC

Dell/recovery_common.py, debian/changelog, grub/recovery_partition.cfg, late/chroot_scripts/03-ubuntu-drivers.sh, ubiquity/dell-bootstrap.py
Slave -> Secondary; blacklist-> blocklist; whitelist->allowlist
=> Non-Exclusive language

late/chroot_scripts/06-dell-recovery-recomends.sh
Some packages are not included in the base image.
Let us install them by a fish script.
=> Install some recommended packages for the recovery media creating.

casper/seeds/ubuntu.seed
Set recovery partition for DHC USB key install
=> Set recovery partition for DHC USB key install

Dell/recovery_common.py
If a file `bypass_vendor_check` exists in the root of the image, bypass the vendor check.
cc @ycheng
=> Add Dell HW check bypass

Dell/recovery_backend.py, Dell/recovery_common.py, gtk/recovery_media_creator.ui, ubiquity/dell-bootstrap.py
…olders for md5sum.txt. (Closes: #166)
=> Fix the content of /var/log/installer/casper-md5check.json and /var/lib/ubuntu_dist_channel

Dell/recovery_backend.py
This can fix the newer dell-recovery Debian packages injection.
=> Fix the distro detection in RP.

ubiquity/dell-bootstrap.py
The output of `parted -l`:
Number  Start   End     Size    File system  Name                  Flags
1      24.6kB  270MB   270MB   fat32        EFI System Partition  boot, esp
2      270MB   8462MB  8192MB  fat32        OS                    msftres
3      8472MB  1999GB  1991GB  ext4
=> Switch ESP from FAT16 to FAT32 and correct RP partition name to OS.

debian/changelog, ubiquity/dell-bootstrap.py
cherry-picked from 963ee0084a5e437037baf7ff49ad74087aea0e64
=> Increase ESP size and change filesystem type from fat16 to fat32 for ESP and RP

late/scripts/pool.sh
The commit sloves DHC dependency issue. And will cut in November block.
=> Add DHC  packages into repo for solving DHC issue

late/scripts/pool.sh
Add DHC releated packages into repo to slove DHC installation dependency issue
=> Add DHC releated packages into repo to slove DHC installation dependency issue
