- late/scripts/oem_config.sh
When creating the recovery media ISO, it needs casper.
If we purge casper, the recovery media ISO will malfunction.
> Don't purge casper. (LP: #1558990)

- debian/control
- debian/dell-recovery-casper.prerm
https://bugs.launchpad.net/bugs/1552621 will remove ubiquity so we recommend it instead of depending on it.
Ubiquity will check dell-recovery-casper.prerm so we prepare an empty script for it.
> Keep dell-recovery-casper not purged by ubiquity. (LP: #1558990)

- late/chroot_scripts/05-enable-oem-config.sh
There are some changes by https://bugs.launchpad.net/bugs/1552621.
We should use `oem-config-prepare --quiet` instead of hacking systemd target.
> Use oem-config-prepare instead of hacking systemd target.

- late/chroot_scripts/02-grub.sh
It is annoying to rebuild or manually input the EFI boot entry after every shutdown.
> Fix the problem that EFI boot configuration cannot be persistent in VirtualBox VM.

- late/chroot_scripts/03-ubuntu-drivers.sh
This patch contains three changes.
The first is to only search for the prefix 'String 2:' or it will also find 'String 20:'.
The second is to lowercase BIOS ID because Debian package doesn't allow uppercase as its package name.
The third is to fix the indent.
> Only search for the prefix 'String 2:' and lowercase the BIOS ID.

- grub/99_dell_recovery
If there are any kernel parameters or other configs were set in the post-rts-gfx.cfg or post-rts-wlan.cfg for factory process, those changes are also required by user manually launched dell-recovery.
> Include post-rts-gfx.cfg and post-rts-wlan.cfg on user launched recovery.

- Dell/recovery_backend.py
There are no 'encoding' and 'errors' for this function call in python3.
> Fix the tarfile usage of python3. Closes: #34

- Dell/recovery_backend.py
- dell-restore-system
- setup.py
Add a new "dell-restore-system" python script under /usr/bin to allow end users to restore the system through command line interface.  This is one of the request required by Wyse team.
dell-restore-system supports following arguments:
-c --check-version: show the version information
-y --yes: restore the system without user's confirmation.
Please note that dell-restore-system could only executed with root privilege.
> Add support to restore the system through command line interface

- Dell/recovery_backend.py
- Dell/recovery_xml.py
- bto-autobuilder/dell-bto-autobuilder
With this commit, we can have clearer information in bto.xml.
For example, if executing the following command.
$ /usr/share/dell/bin/dell-bto-autobuilder -d /tmp/btobuild.RdFsid/manifest.fish -b ../somerville/images/somerville-xenial-amd64-rebase-iso-hybrid-20170712-0.iso --tag X80 --target-name=dell-bto-xenial-italia-X80-iso-20170828-0.iso --target-dir=/home/sylee/projects/oem --target-platform=italia
bto.xml will contain:
```
<bto>
<date>2017-10-05</date>
<versions>
<os/>
<iso>dell-bto-xenial-italia-X80-iso-20170828-0.iso</iso>
<generator>1.50</generator>
<bootstrap/>
<ubiquity/>
<revision>X80</revision>
<platform>italia</platform>
</versions>
<base>somerville-xenial-amd64-rebase-iso-hybrid-20170712-0.iso</base>
```
> Separate revision from iso string, and support platform tag.

- Dell/recovery_basic_gtk.py
- backend/com.dell.recoverymedia.policy.in
- debian/changelog
- ubiquity/dell-bootstrap.py
Check https://git.launchpad.net/ubuntu/+source/partman-swapfile/tree/debian/partman-swapfile.templates for those d-i variables usage.
> Increase the swap file size for hibernate.

- Dell/recovery_backend.py
- debian/changelog
Regarding https://bugs.launchpad.net/bugs/1786432, we will use https://bugs.launchpad.net/bugs/1786153 to provide a template for bionic and then using this patch to renew it for the ISO images.
For example,
```
canonical-oem-somerville-bionic-amd64-20180608-47
```
will  become
```
canonical-oem-somerville-bionic-amd64-20180608-47+punisher-whl+X29
```
Next step is to modify the script to generate superset fish tarball so we can track the specific platform by ubuntu-report.
> Renew .disk/ubuntu_dist_channel for ubuntu-report.

- debian/changelog
- late/chroot_scripts/03-ubuntu-drivers.sh
This would like to use a hook to simplify the usage of fish chroot script and fish tarball.
For example, the original nvidia-driver-410.73-0ubuntu0-bionic_fish1.tar.gz looks like the following:
> ./nvidia-id-list
> ./scripts/chroot-scripts/fish/05-gfx-nvidia.sh
> ./nvidia-410.73/\*.deb
> ./prepackage.dell
> ./nvidia-common/\*.deb
> ./prime-select-intel/config-prime-select-intel-all_0.16_all.deb 
After using this mechanism, it will become:
> ./nvidia-id-list
> ./scripts/chroot-scripts/blacklist/05-gfx-nvidia.list
> ./scripts/chroot-scripts/fish/05-gfx-nvidia.sh
> ./prepackage.dell
> ./debs/\*.deb
We would like to gather all Debian packages under ./debs/.
> Support UBUNTU_DRIVERS_BLACKLIST mechanism in fish tarball.

- casper/seeds/ubuntu.seed
- ubiquity/dell-bootstrap.py
It's much better than what we were adopting (needlessly wasting space)
> Secondly, the sizing of swapfiles is very different. It is no more than 5% of free disk space or 2GiB, whichever is lower.
See https://blog.surgut.co.uk/2016/12/swapfiles-by-default-in-ubuntu.html
for more details.
> dell-bootstrap: use distro policy for swap (Fixes: #82) (LP: #1842325)

- debian/control
I should have looked more closely before merging #90.
Some of this was already fixed in f9af43f45b4d33c4a509a91105ae6ef13080ac40.  So remove the extra duplicates and sort the list.
> trivial: remove duplicated dependencies

- Dell/recovery_common.py
When the initramfs.conf is not in main/conf, the bto build will stop.
I checked the initrd in focal, the initramfs.conf is in conf.
Add the condition to make the flexibility.
> Avoid bto build failure

- late/chroot_scripts/03-ubuntu-drivers.sh
Using `dpkg-query -W -f='${Status}\n' $pkg | grep "install ok installed"` instead.
We met some problem when dealing with the logo customization.
$ sudo dpkg -i dell-canonical-estar-logo_1_all.deb 
(Reading database ... 152000 files and directories currently installed.)
Preparing to unpack dell-canonical-estar-logo_1_all.deb ...
Removing 'diversion of /usr/share/icons/hicolor/256x256/apps/ubuntu-logo-icon.png to /usr/share/icons/hicolor/256x256/apps/ubuntu-logo-icon.png.gnome-conrol-center-data by dell-canonical-estar-logo'
Unpacking dell-canonical-estar-logo (1) over (1) ...
Setting up dell-canonical-estar-logo (1) ...
Adding 'diversion of /usr/share/icons/hicolor/256x256/apps/ubuntu-logo-icon.png to /usr/share/icons/hicolor/256x256/apps/ubuntu-logo-icon.png.gnome-conrol-center-data by …
> Using `dpkg-query -W $pkg` is unreliable.

- late/chroot_scripts/03-ubuntu-drivers.sh
Since the dell-$BIOS_ID-meta is retired, we remove the install script.
> Retire the dell-$BIOS_ID-meta

- debian/changelog
- ubiquity/dell-bootstrap.py
dell-recovery (1.64somerville4) focal; urgency=medium
* ubiquity/dell-bootstrap.py: cherry-pick commit that properly show model
name of certain optane modules.
-- Yuan-Chen Cheng <yc.cheng@canonical.com>  Fri, 22 May 2020 16:43:29 +0800
> Focal optane fix

- Dell/recovery_backend.py
- debian/changelog
- ubiquity/dell-bootstrap.py
we can just disable in stage2. The network just back to work after (and include) OOBE.
> Disable net in stage2 close#114

- debian/changelog
- ubiquity/dell-bootstrap.py
ubiquity/dell-bootstrap.py: delay 5 seconds in dev mode to make it more
reliable, especially for Recovery from hdd.
use the code with this patch in dev environment for quite a while and works well.
> delay 5 seconds for go_forward in dev mode to make it more reliable

- late/scripts/chroot.sh
error log in chroot.sh.log
+ grep /target/pts
+ -e /target/pts
/usr/share/dell/scripts/chroot.sh: 84: -e: not found
+ mkdir -p /target/pts
+ DIR_CLEANUP=/target/pts 
I think this commit fix this issue.
> late/scripts/chroot.sh: syntax error fix

- Dell/recovery_backend.py
- late/scripts/chroot.sh
With recent build of Ubuntu official releases, e.g. Ubuntu Desktop 20.10, missing `isolinux` directory nor `efi.img` file that were referenced previously.
Running `dell-recovery --builder` with Ubuntu 20.10 based ISO will get errors, for example:
```
Unable to locate isolinux to build hybrid MBR
```
and
```
Unable to locate EFI bootloader image
```
> fix for syntax error, and remove the checks for unused boot files

- Dell/recovery_common.py
Because Kylin version format starts with a letter, so we deal with to  make sure OS version start with a digit.
>   Compatible with Kylin OS version format

- late/chroot_scripts/03-ubuntu-drivers.sh
Getting BIOS ID from /sys/devices/virtual/dmi/id/product_sku may be
problematic because of incomplete DMI tables sometimes.
Getting BIOS ID from the subsystem device of host bridge, i.e.
/sys/bus/pci/devices/0000:00:00.0/subsystem_device will be more
reliable.
Relative private bug: https://bugs.launchpad.net/bugs/1917603
> Getting BIOS ID from the subsystem device of host bridge

- late/chroot_scripts/03-ubuntu-drivers.sh
Getting BIOS ID from the subsystem device of host bridge is still
problematic so getting BIOS ID from the subsystem device of i2c device instead.
> Getting BIOS ID from the subsystem device of i2c device

- debian/changelog
- debian/dell-recovery.templates
- ubiquity/dell-bootstrap.py
Add seed value for the minimal recovery partition size. This is useful for the development phase.
This is tested in the focal branch and it works fine.
The preseed sample like:
dell-recovery dell-recovery/recovery_size string 6144
> add seed value for minimal recovery partition size.

- Dell/recovery_common.py
When dell-recovery installed a recovery partition onto eMMC drive then reboot, it finds `/dev/mmcblk0boot1` as the parent device of `/dev/mmcblk0p2` and errornously considering the installer is still in stage 1.
This commit fixes installations on MMC drives by skipping searching MMC boot partitions (`/dev/mmcblk0boot1` etc.) as the parent device.
> Fix installations on eMMC drives

- debian/changelog
- ubiquity/dell-bootstrap.py
https://bugs.launchpad.net/somerville/+bug/1993367
It tries to install Nvidia driver required package during verifying installation configuration. The procedure will be stuck in Dell FI environment. Set it to false to omit the ubuntu-drivers install on DGPU config.
> Don't install packages from external archive in prepare page

- bto-autobuilder/dell-bto-autobuilder
- debian/control
python3-progressbar is not in main/restricted and we would like to reduce the usage of packages that's not supported by Canonical.  Hence, we would like to make it optional.
> dell-bto-autobuilder: make python3-progressbar optional
